### ISSUE TITLE
Space needed on the cards

### ISSUE THREAD

**Issue by krishabbashyal** [SumanSubedi9/Omnifood-Project-Clone-Website#1]
![image](https://github.com/SumanSubedi9/Omnifood-Project-Clone-Website/assets/68142356/32d66337-ea94-41be-ae82-0bdcf40908d0)

**Comment by krishabbashyal** [comment]
@SumanSubedi9 Please resolve this issue asap as it is ruining the user experience

**Comment by krishabbashyal** [comment]
i love open source

**Comment by SumanSubedi9** [comment]
wth

**Comment by krishabbashyal** [comment]
Fantastic
